import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from "app/(shared)/Navbar";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Fakes News App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={inter.className}>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
